### ISSUE TITLE
Requires Java 21

### ISSUE THREAD

**Issue by anm-cb** [nhubbard/konf#1]
The class files are actually compiled in Bytecode-version 65.0 (Java 21) , so there's probably some configuration error in the gradle. I am not sure why exactly but personally I back away from "jvmToolchain" in current gradle version, because it does not seem to do what I wanted it to do.

**Comment by nhubbard** [comment]
Release v2.1.0 should fix this. It should be available shortly on Maven Central. I intended to reduce the JVM target to 11 a while back, but it fell into my backlog for a while.

**Comment by anm-cb** [comment]
Seems to work nicely with Java 11 now, thanks. :+1:
